# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minecraft:
  gamemode: "survival"
  motd: "MineKubed" # Message of the Day
  port: 25565
  mod:
    javamemory: 10G # If increased, update resources limit to be 1-2GB more than this value
    type: "FORGE" # Types: AUTO_CURSEFORGE / FTBA ; Check here for how to set modpack type https://github.com/itzg/docker-minecraft-server/blob/master/README.md#server-types
    # New server types besides curseforge / ftb need new variables added in the deployment.yaml
    # modpack: 'another-quality-modpack-2' # Can be used for either FTB or Curseforge values: Check for details about how to specify modpack ID here https://github.com/itzg/docker-minecraft-server/blob/master/README.md#running-a-server-with-a-feed-the-beast-modpack
    # modpackversion: '1.2.4' # Modpack Server Version
    # modpackstoragename: 'aqm2' # Use for reusing old world data storage; Change name on updating modpack, change back to reuse old saves
    modpackurl: "http://downloads.gtnewhorizons.com/ServerPacks/GT_New_Horizons_2.3.0_Server_Java_17-19.zip"
    modpackstoragename: "gtnewhorizonsnew"
  version: "1.7.10" # Minecraft Version

volume:
  storage: 15Gi # Don't touch
  path: "/mnt/local-volumes/minecraft" # Don't touch
  storageClass: local-path # Do touch

# Don't touch
resources:
  limits:
    memory: 12Gi

# Don't touch
serviceAccount:
  create: true
