# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.minecraft.mod.javamemory }}
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: {{ .Values.minecraft.gamemode }}
          - name: MOTD
            value: {{ .Values.minecraft.motd }}
          - name: ALLOW_FLIGHT
            value: 'TRUE'
          - name: TYPE
            value: {{ .Values.minecraft.mod.type }}
          - name: CF_SERVER_MOD
            value: {{ .Values.minecraft.mod.modpackid }}
          - name: FTB_MODPACK_ID
            value: {{ .Values.minecraft.mod.modpackid }}
          - name: FTB_MODPACK_VERSION_ID
            value: {{ .Values.minecraft.mod.modpackversion }}
          - name: MEMORY
            value: {{ .Values.minecraft.mod.javamemory }}

        ports:
        - containerPort: {{ .Values.minecraft.port }}
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        livenessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          failureThreshold: 5
          initialDelaySeconds: 360
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: minecraft-server
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          failureThreshold: 5
          initialDelaySeconds: 360
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
