apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  serviceName: minecraft-server
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc-{{ .Values.minecraft.mod.modpackstoragename }}
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:java8
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.minecraft.mod.javamemory }}
        env:
          - name:  EULA
            value: 'TRUE'
          - name: GUI
            value: 'FALSE'
          - name: MODE
            value: {{ .Values.minecraft.gamemode | quote }}
          - name: MOTD
            value: {{ .Values.minecraft.motd | quote  }}
          - name: ALLOW_FLIGHT
            value: 'TRUE'
          - name: TYPE
            value: {{ .Values.minecraft.mod.type | quote  }}
          - name: CF_SLUG
            value: {{ .Values.minecraft.mod.modpackid | quote  }}
          - name: MEMORY
            value: {{ .Values.minecraft.mod.javamemory }}
          - name: CF_SERVER_MOD
            value: {{ .Values.minecraft.mod.modpackurl | quote  }}
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                name: cf-api-key
                key: key
        ports:
        - containerPort: {{ .Values.minecraft.port }}
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - 127.0.0.1
          failureThreshold: 5
          initialDelaySeconds: 180
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: minecraft-server
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - 127.0.0.1
          failureThreshold: 5
          initialDelaySeconds: 180
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
