kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
