kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc-{{ .Values.minecraft.mod.modpackstoragename }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.minecraft.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
